version: '3.1'

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "djdyl/tutorial-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "djdyl/tutorial-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"


      # db:
      #   image: mysql
      #   restart: always
      #   container_name: mysql5
      #   ports:
      #     - 3307:3306
      #   environment:
      #     MYSQL_ROOT_PASSWORD: dylanE19
      #     MYSQL_DATABASE: tutorialDatabase
      #     MYSQL_HOST: localhost
      #     MYSQL_USER: root 