version: '2'

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "djdyl/sql-tutorial-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "djdyl/sql-tutorial-frontend"
    ports:
      - "80:3000"
    links:
      - "backend"